import 'package:flutter/material.dart';
import 'package:tu_comida/widgets/ActionsItem.dart';
import 'package:tu_comida/widgets/ActionsList.dart';
import 'package:tu_comida/widgets/CatalogItem.dart';

class MyActions extends StatefulWidget {
  @override
  _MyActionsPageState createState() => _MyActionsPageState();
}

class _MyActionsPageState extends State<MyActions> {
  @override
  Widget build(BuildContext context) {
    var screenWidth = MediaQuery.of(context).size.width / 100;
    var screenHeight = MediaQuery.of(context).size.height / 100;
    return Scaffold(
        backgroundColor: Colors.grey.shade50,
        body: SafeArea(
            child: ListView(
          children: <Widget>[
            //expandedHeight: 100,
            Padding(
              padding: EdgeInsets.only(left: 20.0, top: 10, bottom: 10),
              child: Text('Actions',
                  style: TextStyle(
                      fontSize: screenWidth * 7, color: Colors.black87)),
            ),
            ActionsList(
              actionText: 'Discounts',
              items: [
                ActionsItem(
                  rebajaImage: Image.asset(
                    'assets/stories/stories1.jpg',
                    fit: BoxFit.cover,
                  ),
                  rebajaDescription: '15% discount if you buy a combo',
                  rebajaTime: 12,
                  time: 50,
                  price: 2.75,
                  address: 'Acosta/Goicuria & Mayia Rodriguez ',
                  descriptionInfo:
                      'Burger King offers the best Fast Food. The best choice with the best prices. We have food quality, and reliable suppliers. We are everyone´s preference.    ',
                  workingDays: 'No days off',
                  workingHours: '6 AM _ 2 AM',
                  description: '15% discount if you buy a combo',
                  image: Image.asset(
                    'assets/comida/food4.jpg',
                    fit: BoxFit.cover,
                  ),
                  logo: Image.asset(
                    'assets/logos/burger_king.jfif',
                    fit: BoxFit.cover,
                  ),
                  restaurant: 'Burger King',
                  initDelivery: 0,
                  finalDelivery: 2,
                  priceRange: 20,
                  classification1: 'Popular',
                  cant1: 2,
                  classification2: 'Snacks',
                  cant2: 3,
                  classification3: 'Sandwiches',
                  cant3: 7,
                  classification4: 'Drinks',
                  cant4: 3,
                  classification5: 'Hamburgers',
                  cant5: 1,
                  classification6: 'Desserts',
                  cant6: 8,
                  products: [
                    CatalogItem(
                      image: Image.asset('assets/comida/food4.jpg',
                          fit: BoxFit.cover),
                      productName: 'Hamburgers with fries',
                      productPrice: 5.30,
                      description: '2 Hamburgers with a pack of fries',
                      theme1: 'Cheese',
                      only1: 'Gouda Cheese',
                      only2: 'Blue Cheese',
                      theme2: 'Meat',
                      theme3: 'Sauce',
                      only3: 'Pork',
                      only4: 'Chicken',
                      optional1: 'Teriyaki Sauce',
                      optional2: 'Cheese Sauce',
                      optional3: 'Invented Sauce',
                      cant: 0,
                    ),
                    CatalogItem(
                      image: Image.asset('assets/comida/food6.jpg',
                          fit: BoxFit.cover),
                      productName: 'Paella',
                      productPrice: 7,
                      description: 'Paella with Shrimps and eggs',
                      theme1: 'Cheese',
                      only1: 'Gouda Cheese',
                      only2: 'Blue Cheese',
                      theme2: 'Meat',
                      theme3: 'Sauce',
                      only3: 'Pork',
                      only4: 'Chicken',
                      optional1: 'Teriyaki Sauce',
                      optional2: 'Cheese Sauce',
                      optional3: 'Invented Sauce',
                      cant: 0,
                    ),
                    CatalogItem(
                      image: Image.asset('assets/comida/food4.jpg',
                          fit: BoxFit.cover),
                      productName: 'Hamburgers with fries',
                      productPrice: 3.30,
                      description: '1 Hamburgers with a pack of fries',
                      theme1: 'Cheese',
                      only1: 'Gouda Cheese',
                      only2: 'Blue Cheese',
                      theme2: 'Meat',
                      theme3: 'Sauce',
                      only3: 'Pork',
                      only4: 'Chicken',
                      optional1: 'Teriyaki Sauce',
                      optional2: 'Cheese Sauce',
                      optional3: 'Invented Sauce',
                      cant: 0,
                    ),
                    CatalogItem(
                      image: Image.asset('assets/comida/food6.jpg',
                          fit: BoxFit.cover),
                      productName: 'Paella',
                      productPrice: 2,
                      description: 'Paella with Shrimps',
                      theme1: 'Cheese',
                      only1: 'Gouda Cheese',
                      only2: 'Blue Cheese',
                      theme2: 'Meat',
                      theme3: 'Sauce',
                      only3: 'Pork',
                      only4: 'Chicken',
                      optional1: 'Teriyaki Sauce',
                      optional2: 'Cheese Sauce',
                      optional3: 'Invented Sauce',
                      cant: 0,
                    ),
                  ],
                ),
                ActionsItem(
                  rebajaImage: Image.asset(
                    'assets/stories/stories1.jpg',
                    fit: BoxFit.cover,
                  ),
                  rebajaDescription: '15% discount if you buy a combo',
                  rebajaTime: 12,
                  time: 50,
                  price: 2.75,
                  address: 'Acosta/Goicuria & Mayia Rodriguez ',
                  descriptionInfo:
                      'Burger King offers the best Fast Food. The best choice with the best prices. We have food quality, and reliable suppliers. We are everyone´s preference.    ',
                  workingDays: 'No days off',
                  workingHours: '6 AM _ 2 AM',
                  description: '15% discount if you buy a combo',
                  image: Image.asset(
                    'assets/comida/food4.jpg',
                    fit: BoxFit.cover,
                  ),
                  logo: Image.asset(
                    'assets/logos/burger_king.jfif',
                    fit: BoxFit.cover,
                  ),
                  restaurant: 'Burger King',
                  initDelivery: 0,
                  finalDelivery: 2,
                  priceRange: 20,
                  classification1: 'Popular',
                  cant1: 2,
                  classification2: 'Snacks',
                  cant2: 3,
                  classification3: 'Sandwiches',
                  cant3: 7,
                  classification4: 'Drinks',
                  cant4: 3,
                  classification5: 'Hamburgers',
                  cant5: 1,
                  classification6: 'Desserts',
                  cant6: 8,
                  products: [
                    CatalogItem(
                      image: Image.asset('assets/comida/food4.jpg',
                          fit: BoxFit.cover),
                      productName: 'Hamburgers with fries',
                      productPrice: 5.30,
                      description: '2 Hamburgers with a pack of fries',
                      theme1: 'Cheese',
                      only1: 'Gouda Cheese',
                      only2: 'Blue Cheese',
                      theme2: 'Meat',
                      theme3: 'Sauce',
                      only3: 'Pork',
                      only4: 'Chicken',
                      optional1: 'Teriyaki Sauce',
                      optional2: 'Cheese Sauce',
                      optional3: 'Invented Sauce',
                      cant: 0,
                    ),
                    CatalogItem(
                      image: Image.asset('assets/comida/food6.jpg',
                          fit: BoxFit.cover),
                      productName: 'Paella',
                      productPrice: 7,
                      description: 'Paella with Shrimps and eggs',
                      theme1: 'Cheese',
                      only1: 'Gouda Cheese',
                      only2: 'Blue Cheese',
                      theme2: 'Meat',
                      theme3: 'Sauce',
                      only3: 'Pork',
                      only4: 'Chicken',
                      optional1: 'Teriyaki Sauce',
                      optional2: 'Cheese Sauce',
                      optional3: 'Invented Sauce',
                      cant: 0,
                    ),
                    CatalogItem(
                      image: Image.asset('assets/comida/food4.jpg',
                          fit: BoxFit.cover),
                      productName: 'Hamburgers with fries',
                      productPrice: 3.30,
                      description: '1 Hamburgers with a pack of fries',
                      theme1: 'Cheese',
                      only1: 'Gouda Cheese',
                      only2: 'Blue Cheese',
                      theme2: 'Meat',
                      theme3: 'Sauce',
                      only3: 'Pork',
                      only4: 'Chicken',
                      optional1: 'Teriyaki Sauce',
                      optional2: 'Cheese Sauce',
                      optional3: 'Invented Sauce',
                      cant: 0,
                    ),
                    CatalogItem(
                      image: Image.asset('assets/comida/food6.jpg',
                          fit: BoxFit.cover),
                      productName: 'Paella',
                      productPrice: 2,
                      description: 'Paella with Shrimps',
                      theme1: 'Cheese',
                      only1: 'Gouda Cheese',
                      only2: 'Blue Cheese',
                      theme2: 'Meat',
                      theme3: 'Sauce',
                      only3: 'Pork',
                      only4: 'Chicken',
                      optional1: 'Teriyaki Sauce',
                      optional2: 'Cheese Sauce',
                      optional3: 'Invented Sauce',
                      cant: 0,
                    ),
                  ],
                ),
              ],
            ),
            ActionsList(items: [
              ActionsItem(
                description: '12% for orders above 20cuc',
                restaurant: 'Domino´s Pizza',
                time: 30,
                price: 4.25,
                initDelivery: 2,
                finalDelivery: 5,
                priceRange: 25,
                classification1: 'Popular',
                cant1: 2,
                classification2: 'Snacks',
                cant2: 4,
                classification3: 'Salads',
                cant3: 9,
                classification4: 'Drinks',
                cant4: 3,
                classification5: 'Pizzas',
                cant5: 5,
                classification6: 'Desserts',
                cant6: 2,
                products: [
                  CatalogItem(
                    image: Image.asset('assets/comida/food4.jpg',
                        fit: BoxFit.cover),
                    productName: 'Hamburgers with fries',
                    productPrice: 5.30,
                    description: '2 Hamburgers with a pack of fries',
                    theme1: 'Cheese',
                    only1: 'Gouda Cheese',
                    only2: 'Blue Cheese',
                    theme2: 'Meat',
                    theme3: 'Sauce',
                    only3: 'Pork',
                    only4: 'Chicken',
                    optional1: 'Teriyaki Sauce',
                    optional2: 'Cheese Sauce',
                    optional3: 'Invented Sauce',
                    cant: 0,
                  ),
                  CatalogItem(
                    image: Image.asset('assets/comida/food6.jpg',
                        fit: BoxFit.cover),
                    productName: 'Paella',
                    productPrice: 7,
                    description: 'Paella with Shrimps and eggs',
                    theme1: 'Cheese',
                    only1: 'Gouda Cheese',
                    only2: 'Blue Cheese',
                    theme2: 'Meat',
                    theme3: 'Sauce',
                    only3: 'Pork',
                    only4: 'Chicken',
                    optional1: 'Teriyaki Sauce',
                    optional2: 'Cheese Sauce',
                    optional3: 'Invented Sauce',
                    cant: 0,
                  ),
                  CatalogItem(
                    image: Image.asset('assets/comida/food4.jpg',
                        fit: BoxFit.cover),
                    productName: 'Hamburgers with fries',
                    productPrice: 3.30,
                    description: '1 Hamburgers with a pack of fries',
                    theme1: 'Cheese',
                    only1: 'Gouda Cheese',
                    only2: 'Blue Cheese',
                    theme2: 'Meat',
                    theme3: 'Sauce',
                    only3: 'Pork',
                    only4: 'Chicken',
                    optional1: 'Teriyaki Sauce',
                    optional2: 'Cheese Sauce',
                    optional3: 'Invented Sauce',
                    cant: 0,
                  ),
                  CatalogItem(
                    image: Image.asset('assets/comida/food6.jpg',
                        fit: BoxFit.cover),
                    productName: 'Paella',
                    productPrice: 2,
                    description: 'Paella with Shrimps',
                    theme1: 'Cheese',
                    only1: 'Gouda Cheese',
                    only2: 'Blue Cheese',
                    theme2: 'Meat',
                    theme3: 'Sauce',
                    only3: 'Pork',
                    only4: 'Chicken',
                    optional1: 'Teriyaki Sauce',
                    optional2: 'Cheese Sauce',
                    optional3: 'Invented Sauce',
                    cant: 0,
                  ),
                ],
                rebajaImage: Image.asset(
                  'assets/stories/stories1.jpg',
                  fit: BoxFit.cover,
                ),
                rebajaDescription: '12% for orders above 20cuc',
                rebajaTime: 12,
                address: 'Acosta/Goicuria & Mayia Rodriguez ',
                descriptionInfo:
                    'Domino´s Pizza offers the best Fast Food. The best choice with the best prices  ',
                workingDays: 'No days off',
                workingHours: '6 AM _ 2 AM',
                image: Image.asset(
                  'assets/comida/food6.jpg',
                  fit: BoxFit.cover,
                ),
                logo: Image.asset(
                  'assets/logos/dominos_pizza.png',
                  fit: BoxFit.cover,
                ),
              ),
              ActionsItem(
                description: '12% for orders above 20cuc',
                restaurant: 'Domino´s Pizza',
                time: 30,
                price: 4.25,
                initDelivery: 2,
                finalDelivery: 5,
                priceRange: 25,
                classification1: 'Popular',
                cant1: 2,
                classification2: 'Snacks',
                cant2: 4,
                classification3: 'Salads',
                cant3: 9,
                classification4: 'Drinks',
                cant4: 3,
                classification5: 'Pizzas',
                cant5: 5,
                classification6: 'Desserts',
                cant6: 2,
                products: [
                  CatalogItem(
                    image: Image.asset('assets/comida/food4.jpg',
                        fit: BoxFit.cover),
                    productName: 'Hamburgers with fries',
                    productPrice: 5.30,
                    description: '2 Hamburgers with a pack of fries',
                    theme1: 'Cheese',
                    only1: 'Gouda Cheese',
                    only2: 'Blue Cheese',
                    theme2: 'Meat',
                    theme3: 'Sauce',
                    only3: 'Pork',
                    only4: 'Chicken',
                    optional1: 'Teriyaki Sauce',
                    optional2: 'Cheese Sauce',
                    optional3: 'Invented Sauce',
                    cant: 0,
                  ),
                  CatalogItem(
                    image: Image.asset('assets/comida/food6.jpg',
                        fit: BoxFit.cover),
                    productName: 'Paella',
                    productPrice: 7,
                    description: 'Paella with Shrimps and eggs',
                    theme1: 'Cheese',
                    only1: 'Gouda Cheese',
                    only2: 'Blue Cheese',
                    theme2: 'Meat',
                    theme3: 'Sauce',
                    only3: 'Pork',
                    only4: 'Chicken',
                    optional1: 'Teriyaki Sauce',
                    optional2: 'Cheese Sauce',
                    optional3: 'Invented Sauce',
                    cant: 0,
                  ),
                  CatalogItem(
                    image: Image.asset('assets/comida/food4.jpg',
                        fit: BoxFit.cover),
                    productName: 'Hamburgers with fries',
                    productPrice: 3.30,
                    description: '1 Hamburgers with a pack of fries',
                    theme1: 'Cheese',
                    only1: 'Gouda Cheese',
                    only2: 'Blue Cheese',
                    theme2: 'Meat',
                    theme3: 'Sauce',
                    only3: 'Pork',
                    only4: 'Chicken',
                    optional1: 'Teriyaki Sauce',
                    optional2: 'Cheese Sauce',
                    optional3: 'Invented Sauce',
                    cant: 0,
                  ),
                  CatalogItem(
                    image: Image.asset('assets/comida/food6.jpg',
                        fit: BoxFit.cover),
                    productName: 'Paella',
                    productPrice: 2,
                    description: 'Paella with Shrimps',
                    theme1: 'Cheese',
                    only1: 'Gouda Cheese',
                    only2: 'Blue Cheese',
                    theme2: 'Meat',
                    theme3: 'Sauce',
                    only3: 'Pork',
                    only4: 'Chicken',
                    optional1: 'Teriyaki Sauce',
                    optional2: 'Cheese Sauce',
                    optional3: 'Invented Sauce',
                    cant: 0,
                  ),
                ],
                rebajaImage: Image.asset(
                  'assets/stories/stories1.jpg',
                  fit: BoxFit.cover,
                ),
                rebajaDescription: '12% for orders above 20cuc',
                rebajaTime: 12,
                address: 'Acosta/Goicuria & Mayia Rodriguez ',
                descriptionInfo:
                    'Domino´s Pizza offers the best Fast Food. The best choice with the best prices  ',
                workingDays: 'No days off',
                workingHours: '6 AM _ 2 AM',
                image: Image.asset(
                  'assets/comida/food6.jpg',
                  fit: BoxFit.cover,
                ),
                logo: Image.asset(
                  'assets/logos/dominos_pizza.png',
                  fit: BoxFit.cover,
                ),
              ),
            ], actionText: 'Happy hours'),
            ActionsList(items: [
              ActionsItem(
                description: '12% for orders above 20cuc',
                restaurant: 'Domino´s Pizza',
                time: 30,
                price: 4.25,
                initDelivery: 2,
                finalDelivery: 5,
                priceRange: 25,
                classification1: 'Popular',
                cant1: 2,
                classification2: 'Snacks',
                cant2: 4,
                classification3: 'Salads',
                cant3: 9,
                classification4: 'Drinks',
                cant4: 3,
                classification5: 'Pizzas',
                cant5: 5,
                classification6: 'Desserts',
                cant6: 2,
                products: [
                  CatalogItem(
                    image: Image.asset('assets/comida/food4.jpg',
                        fit: BoxFit.cover),
                    productName: 'Hamburgers with fries',
                    productPrice: 5.30,
                    description: '2 Hamburgers with a pack of fries',
                    theme1: 'Cheese',
                    only1: 'Gouda Cheese',
                    only2: 'Blue Cheese',
                    theme2: 'Meat',
                    theme3: 'Sauce',
                    only3: 'Pork',
                    only4: 'Chicken',
                    optional1: 'Teriyaki Sauce',
                    optional2: 'Cheese Sauce',
                    optional3: 'Invented Sauce',
                    cant: 0,
                  ),
                  CatalogItem(
                    image: Image.asset('assets/comida/food6.jpg',
                        fit: BoxFit.cover),
                    productName: 'Paella',
                    productPrice: 7,
                    description: 'Paella with Shrimps and eggs',
                    theme1: 'Cheese',
                    only1: 'Gouda Cheese',
                    only2: 'Blue Cheese',
                    theme2: 'Meat',
                    theme3: 'Sauce',
                    only3: 'Pork',
                    only4: 'Chicken',
                    optional1: 'Teriyaki Sauce',
                    optional2: 'Cheese Sauce',
                    optional3: 'Invented Sauce',
                    cant: 0,
                  ),
                  CatalogItem(
                    image: Image.asset('assets/comida/food4.jpg',
                        fit: BoxFit.cover),
                    productName: 'Hamburgers with fries',
                    productPrice: 3.30,
                    description: '1 Hamburgers with a pack of fries',
                    theme1: 'Cheese',
                    only1: 'Gouda Cheese',
                    only2: 'Blue Cheese',
                    theme2: 'Meat',
                    theme3: 'Sauce',
                    only3: 'Pork',
                    only4: 'Chicken',
                    optional1: 'Teriyaki Sauce',
                    optional2: 'Cheese Sauce',
                    optional3: 'Invented Sauce',
                    cant: 0,
                  ),
                  CatalogItem(
                    image: Image.asset('assets/comida/food6.jpg',
                        fit: BoxFit.cover),
                    productName: 'Paella',
                    productPrice: 2,
                    description: 'Paella with Shrimps',
                    theme1: 'Cheese',
                    only1: 'Gouda Cheese',
                    only2: 'Blue Cheese',
                    theme2: 'Meat',
                    theme3: 'Sauce',
                    only3: 'Pork',
                    only4: 'Chicken',
                    optional1: 'Teriyaki Sauce',
                    optional2: 'Cheese Sauce',
                    optional3: 'Invented Sauce',
                    cant: 0,
                  ),
                ],
                rebajaImage: Image.asset(
                  'assets/stories/stories1.jpg',
                  fit: BoxFit.cover,
                ),
                rebajaDescription: '12% for orders above 20cuc',
                rebajaTime: 12,
                address: 'Acosta/Goicuria & Mayia Rodriguez ',
                descriptionInfo:
                    'Dominos Pizza offers the best Fast Food. The best choice with the best prices  ',
                workingDays: 'No days off',
                workingHours: '6 AM _ 2 AM',
                image: Image.asset(
                  'assets/comida/food6.jpg',
                  fit: BoxFit.cover,
                ),
                logo: Image.asset(
                  'assets/logos/dominos_pizza.png',
                  fit: BoxFit.cover,
                ),
              ),
              ActionsItem(
                rebajaImage: Image.asset(
                  'assets/stories/stories1.jpg',
                  fit: BoxFit.cover,
                ),
                rebajaDescription: '15% discount if you buy a combo',
                rebajaTime: 12,
                time: 50,
                price: 2.75,
                address: 'Acosta/Goicuria & Mayia Rodriguez ',
                descriptionInfo:
                    'Burger King offers the best Fast Food. The best choice with the best prices. We have food quality, and reliable suppliers. We are everyone´s preference.    ',
                workingDays: 'No days off',
                workingHours: '6 AM _ 2 AM',
                description: '15% discount if you buy a combo',
                image: Image.asset(
                  'assets/comida/food4.jpg',
                  fit: BoxFit.cover,
                ),
                logo: Image.asset(
                  'assets/logos/burger_king.jfif',
                  fit: BoxFit.cover,
                ),
                restaurant: 'Burger King',
                initDelivery: 0,
                finalDelivery: 2,
                priceRange: 20,
                classification1: 'Popular',
                cant1: 2,
                classification2: 'Snacks',
                cant2: 3,
                classification3: 'Sandwiches',
                cant3: 7,
                classification4: 'Drinks',
                cant4: 3,
                classification5: 'Hamburgers',
                cant5: 1,
                classification6: 'Desserts',
                cant6: 8,
                products: [
                  CatalogItem(
                    image: Image.asset('assets/comida/food4.jpg',
                        fit: BoxFit.cover),
                    productName: 'Hamburgers with fries',
                    productPrice: 5.30,
                    description: '2 Hamburgers with a pack of fries',
                    theme1: 'Cheese',
                    only1: 'Gouda Cheese',
                    only2: 'Blue Cheese',
                    theme2: 'Meat',
                    theme3: 'Sauce',
                    only3: 'Pork',
                    only4: 'Chicken',
                    optional1: 'Teriyaki Sauce',
                    optional2: 'Cheese Sauce',
                    optional3: 'Invented Sauce',
                    cant: 0,
                  ),
                  CatalogItem(
                    image: Image.asset('assets/comida/food6.jpg',
                        fit: BoxFit.cover),
                    productName: 'Paella',
                    productPrice: 7,
                    description: 'Paella with Shrimps and eggs',
                    theme1: 'Cheese',
                    only1: 'Gouda Cheese',
                    only2: 'Blue Cheese',
                    theme2: 'Meat',
                    theme3: 'Sauce',
                    only3: 'Pork',
                    only4: 'Chicken',
                    optional1: 'Teriyaki Sauce',
                    optional2: 'Cheese Sauce',
                    optional3: 'Invented Sauce',
                    cant: 0,
                  ),
                  CatalogItem(
                    image: Image.asset('assets/comida/food4.jpg',
                        fit: BoxFit.cover),
                    productName: 'Hamburgers with fries',
                    productPrice: 3.30,
                    description: '1 Hamburgers with a pack of fries',
                    theme1: 'Cheese',
                    only1: 'Gouda Cheese',
                    only2: 'Blue Cheese',
                    theme2: 'Meat',
                    theme3: 'Sauce',
                    only3: 'Pork',
                    only4: 'Chicken',
                    optional1: 'Teriyaki Sauce',
                    optional2: 'Cheese Sauce',
                    optional3: 'Invented Sauce',
                    cant: 0,
                  ),
                  CatalogItem(
                    image: Image.asset('assets/comida/food6.jpg',
                        fit: BoxFit.cover),
                    productName: 'Paella',
                    productPrice: 2,
                    description: 'Paella with Shrimps',
                    theme1: 'Cheese',
                    only1: 'Gouda Cheese',
                    only2: 'Blue Cheese',
                    theme2: 'Meat',
                    theme3: 'Sauce',
                    only3: 'Pork',
                    only4: 'Chicken',
                    optional1: 'Teriyaki Sauce',
                    optional2: 'Cheese Sauce',
                    optional3: 'Invented Sauce',
                    cant: 0,
                  ),
                ],
              ),
            ], actionText: 'Product as a gift'),
          ],
        )));
  }
}
