import 'package:flutter/material.dart';
import 'package:tu_comida/widgets/StoriesItem.dart';
import 'CatalogItem.dart';
import 'PlaceItem.dart';

class StoriesList extends StatefulWidget {
  @override
  _StoriesListState createState() => _StoriesListState();
}

class _StoriesListState extends State<StoriesList> {
  @override
  Widget build(BuildContext context) {
    var screenWidth = MediaQuery.of(context).size.width / 100;
    var screenHeight = MediaQuery.of(context).size.height / 100;
    return Padding(
      padding: EdgeInsets.only(
        top: screenHeight * 2,
      ),
      child: Container(
        margin: EdgeInsets.only(
            left: screenWidth * 2.5, bottom: screenHeight * 1.5),
        height: screenHeight * 13.5,
        child: ListView(
          primary: false,
          shrinkWrap: true,
          scrollDirection: Axis.horizontal,
          children: <Widget>[
            StoriesItem(
              places: [
                PlaceItem(
                  image: Image.asset(
                    'assets/comida/food4.jpg',
                    fit: BoxFit.cover,
                  ),
                  restaurant: 'BurgerKing',
                  logo: Image.asset(
                    'assets/logos/burger_king.jfif',
                    fit: BoxFit.cover,
                  ),
                  rebajaImage: Image.asset(
                    'assets/stories/stories1.jpg',
                    fit: BoxFit.cover,
                  ),
                  rebajaDescription: '15% discount if you buy a combo',
                  rebajaTime: 12,
                  time: 50,
                  price: 2.75,
                  initDelivery: 0,
                  finalDelivery: 2,
                  priceRange: 20,
                  classification1: 'Popular',
                  cant1: 2,
                  classification2: 'Snacks',
                  cant2: 3,
                  classification3: 'Sandwiches',
                  cant3: 7,
                  classification4: 'Drinks',
                  cant4: 3,
                  classification5: 'Hamburgers',
                  cant5: 1,
                  classification6: 'Desserts',
                  cant6: 8,
                  products: [
                    CatalogItem(
                      image: Image.asset('assets/comida/food4.jpg',
                          fit: BoxFit.cover),
                      productName: 'Hamburgers with fries',
                      productPrice: 5.30,
                      description: '2 Hamburgers with a pack of fries',
                      theme1: 'Cheese',
                      only1: 'Gouda Cheese',
                      only2: 'Blue Cheese',
                      theme2: 'Meat',
                      theme3: 'Sauce',
                      only3: 'Pork',
                      only4: 'Chicken',
                      optional1: 'Teriyaki Sauce',
                      optional2: 'Cheese Sauce',
                      optional3: 'Invented Sauce',
                      cant: 0,
                    ),
                    CatalogItem(
                      image: Image.asset('assets/comida/food6.jpg',
                          fit: BoxFit.cover),
                      productName: 'Paella',
                      productPrice: 7,
                      description: 'Paella with Shrimps and eggs',
                      theme1: 'Cheese',
                      only1: 'Gouda Cheese',
                      only2: 'Blue Cheese',
                      theme2: 'Meat',
                      theme3: 'Sauce',
                      only3: 'Pork',
                      only4: 'Chicken',
                      optional1: 'Teriyaki Sauce',
                      optional2: 'Cheese Sauce',
                      optional3: 'Invented Sauce',
                      cant: 0,
                    ),
                    CatalogItem(
                      image: Image.asset('assets/comida/food4.jpg',
                          fit: BoxFit.cover),
                      productName: 'Hamburgers with fries',
                      productPrice: 3.30,
                      description: '1 Hamburgers with a pack of fries',
                      theme1: 'Cheese',
                      only1: 'Gouda Cheese',
                      only2: 'Blue Cheese',
                      theme2: 'Meat',
                      theme3: 'Sauce',
                      only3: 'Pork',
                      only4: 'Chicken',
                      optional1: 'Teriyaki Sauce',
                      optional2: 'Cheese Sauce',
                      optional3: 'Invented Sauce',
                      cant: 0,
                    ),
                    CatalogItem(
                      image: Image.asset('assets/comida/food6.jpg',
                          fit: BoxFit.cover),
                      productName: 'Paella',
                      productPrice: 2,
                      description: 'Paella with Shrimps',
                      theme1: 'Cheese',
                      only1: 'Gouda Cheese',
                      only2: 'Blue Cheese',
                      theme2: 'Meat',
                      theme3: 'Sauce',
                      only3: 'Pork',
                      only4: 'Chicken',
                      optional1: 'Teriyaki Sauce',
                      optional2: 'Cheese Sauce',
                      optional3: 'Invented Sauce',
                      cant: 0,
                    ),
                  ],
                  address: 'Acosta/Goicuria & Mayia Rodriguez ',
                  descriptionInfo:
                      'Burger King offers the best Fast Food. The best choice with the best prices. We have food quality, and reliable suppliers. We are everyone´s preference.    ',
                  workingDays: 'No days off',
                  workingHours: '6 AM _ 2 AM',
                ),
                PlaceItem(
                  image: Image.asset(
                    'assets/comida/food4.jpg',
                    fit: BoxFit.cover,
                  ),
                  restaurant: 'BurgerKing',
                  logo: Image.asset(
                    'assets/logos/burger_king.jfif',
                    fit: BoxFit.cover,
                  ),
                  rebajaImage: Image.asset(
                    'assets/stories/stories1.jpg',
                    fit: BoxFit.cover,
                  ),
                  rebajaDescription: '15% discount if you buy a combo',
                  rebajaTime: 12,
                  time: 50,
                  price: 2.75,
                  initDelivery: 0,
                  finalDelivery: 2,
                  priceRange: 20,
                  classification1: 'Popular',
                  cant1: 2,
                  classification2: 'Snacks',
                  cant2: 3,
                  classification3: 'Sandwiches',
                  cant3: 7,
                  classification4: 'Drinks',
                  cant4: 3,
                  classification5: 'Hamburgers',
                  cant5: 1,
                  classification6: 'Desserts',
                  cant6: 8,
                  products: [
                    CatalogItem(
                      image: Image.asset('assets/comida/food4.jpg',
                          fit: BoxFit.cover),
                      productName: 'Hamburgers with fries',
                      productPrice: 5.30,
                      description: '2 Hamburgers with a pack of fries',
                      theme1: 'Cheese',
                      only1: 'Gouda Cheese',
                      only2: 'Blue Cheese',
                      theme2: 'Meat',
                      theme3: 'Sauce',
                      only3: 'Pork',
                      only4: 'Chicken',
                      optional1: 'Teriyaki Sauce',
                      optional2: 'Cheese Sauce',
                      optional3: 'Invented Sauce',
                      cant: 0,
                    ),
                    CatalogItem(
                      image: Image.asset('assets/comida/food6.jpg',
                          fit: BoxFit.cover),
                      productName: 'Paella',
                      productPrice: 7,
                      description: 'Paella with Shrimps and eggs',
                      theme1: 'Cheese',
                      only1: 'Gouda Cheese',
                      only2: 'Blue Cheese',
                      theme2: 'Meat',
                      theme3: 'Sauce',
                      only3: 'Pork',
                      only4: 'Chicken',
                      optional1: 'Teriyaki Sauce',
                      optional2: 'Cheese Sauce',
                      optional3: 'Invented Sauce',
                      cant: 0,
                    ),
                    CatalogItem(
                      image: Image.asset('assets/comida/food4.jpg',
                          fit: BoxFit.cover),
                      productName: 'Hamburgers with fries',
                      productPrice: 3.30,
                      description: '1 Hamburgers with a pack of fries',
                      theme1: 'Cheese',
                      only1: 'Gouda Cheese',
                      only2: 'Blue Cheese',
                      theme2: 'Meat',
                      theme3: 'Sauce',
                      only3: 'Pork',
                      only4: 'Chicken',
                      optional1: 'Teriyaki Sauce',
                      optional2: 'Cheese Sauce',
                      optional3: 'Invented Sauce',
                      cant: 0,
                    ),
                    CatalogItem(
                      image: Image.asset('assets/comida/food6.jpg',
                          fit: BoxFit.cover),
                      productName: 'Paella',
                      productPrice: 2,
                      description: 'Paella with Shrimps',
                      theme1: 'Cheese',
                      only1: 'Gouda Cheese',
                      only2: 'Blue Cheese',
                      theme2: 'Meat',
                      theme3: 'Sauce',
                      only3: 'Pork',
                      only4: 'Chicken',
                      optional1: 'Teriyaki Sauce',
                      optional2: 'Cheese Sauce',
                      optional3: 'Invented Sauce',
                      cant: 0,
                    ),
                  ],
                  address: 'Acosta/Goicuria & Mayia Rodriguez ',
                  descriptionInfo:
                      'Burger King offers the best Fast Food. The best choice with the best prices. We have food quality, and reliable suppliers. We are everyone´s preference.    ',
                  workingDays: 'No days off',
                  workingHours: '6 AM _ 2 AM',
                ),
              ],
              image: Image.asset(
                'assets/stories/stories1.jpg',
                fit: BoxFit.cover,
              ),
              header: 'Discount if you buy a combo',
              title: 'Discount if you buy a combo!',
              description: 'Collect some points and earn a free meal',
            ),
            StoriesItem(
              places: [
                PlaceItem(
                  image: Image.asset(
                    'assets/comida/food7.jpg',
                    fit: BoxFit.cover,
                  ),
                  restaurant: 'Dominos´s Pizza',
                  logo: Image.asset(
                    'assets/logos/dominos_pizza.png',
                    fit: BoxFit.cover,
                  ),
                  time: 30,
                  price: 4.25,
                  initDelivery: 2,
                  finalDelivery: 5,
                  priceRange: 25,
                  classification1: 'Popular',
                  cant1: 2,
                  classification2: 'Snacks',
                  cant2: 4,
                  classification3: 'Salads',
                  cant3: 9,
                  classification4: 'Drinks',
                  cant4: 3,
                  classification5: 'Pizzas',
                  cant5: 5,
                  classification6: 'Desserts',
                  cant6: 2,
                  products: [
                    CatalogItem(
                      image: Image.asset('assets/comida/food4.jpg',
                          fit: BoxFit.cover),
                      productName: 'Hamburgers with fries',
                      productPrice: 5.30,
                      description: '2 Hamburgers with a pack of fries',
                      theme1: 'Cheese',
                      only1: 'Gouda Cheese',
                      only2: 'Blue Cheese',
                      theme2: 'Meat',
                      theme3: 'Sauce',
                      only3: 'Pork',
                      only4: 'Chicken',
                      optional1: 'Teriyaki Sauce',
                      optional2: 'Cheese Sauce',
                      optional3: 'Invented Sauce',
                      cant: 0,
                    ),
                    CatalogItem(
                      image: Image.asset('assets/comida/food6.jpg',
                          fit: BoxFit.cover),
                      productName: 'Paella',
                      productPrice: 7,
                      description: 'Paella with Shrimps and eggs',
                      theme1: 'Cheese',
                      only1: 'Gouda Cheese',
                      only2: 'Blue Cheese',
                      theme2: 'Meat',
                      theme3: 'Sauce',
                      only3: 'Pork',
                      only4: 'Chicken',
                      optional1: 'Teriyaki Sauce',
                      optional2: 'Cheese Sauce',
                      optional3: 'Invented Sauce',
                      cant: 0,
                    ),
                    CatalogItem(
                      image: Image.asset('assets/comida/food4.jpg',
                          fit: BoxFit.cover),
                      productName: 'Hamburgers with fries',
                      productPrice: 3.30,
                      description: '1 Hamburgers with a pack of fries',
                      theme1: 'Cheese',
                      only1: 'Gouda Cheese',
                      only2: 'Blue Cheese',
                      theme2: 'Meat',
                      theme3: 'Sauce',
                      only3: 'Pork',
                      only4: 'Chicken',
                      optional1: 'Teriyaki Sauce',
                      optional2: 'Cheese Sauce',
                      optional3: 'Invented Sauce',
                      cant: 0,
                    ),
                    CatalogItem(
                      image: Image.asset('assets/comida/food6.jpg',
                          fit: BoxFit.cover),
                      productName: 'Paella',
                      productPrice: 2,
                      description: 'Paella with Shrimps',
                      theme1: 'Cheese',
                      only1: 'Gouda Cheese',
                      only2: 'Blue Cheese',
                      theme2: 'Meat',
                      theme3: 'Sauce',
                      only3: 'Pork',
                      only4: 'Chicken',
                      optional1: 'Teriyaki Sauce',
                      optional2: 'Cheese Sauce',
                      optional3: 'Invented Sauce',
                      cant: 0,
                    ),
                  ],
                  rebajaImage: Image.asset(
                    'assets/stories/stories1.jpg',
                    fit: BoxFit.cover,
                  ),
                  rebajaDescription: '12% for orders above 20cuc ',
                  rebajaTime: 12,
                  address: 'Acosta/Goicuria & Mayia Rodriguez ',
                  descriptionInfo:
                      'Domino´s Pizza offers the best Fast Food. The best choice with the best prices  ',
                  workingDays: 'No days off',
                  workingHours: '6 AM _ 2 AM',
                ),
                PlaceItem(
                  image: Image.asset(
                    'assets/comida/food7.jpg',
                    fit: BoxFit.cover,
                  ),
                  restaurant: 'Dominos´s Pizza',
                  logo: Image.asset(
                    'assets/logos/dominos_pizza.png',
                    fit: BoxFit.cover,
                  ),
                  time: 30,
                  price: 4.25,
                  initDelivery: 2,
                  finalDelivery: 5,
                  priceRange: 25,
                  classification1: 'Popular',
                  cant1: 2,
                  classification2: 'Snacks',
                  cant2: 4,
                  classification3: 'Salads',
                  cant3: 9,
                  classification4: 'Drinks',
                  cant4: 3,
                  classification5: 'Pizzas',
                  cant5: 5,
                  classification6: 'Desserts',
                  cant6: 2,
                  products: [
                    CatalogItem(
                      image: Image.asset('assets/comida/food4.jpg',
                          fit: BoxFit.cover),
                      productName: 'Hamburgers with fries',
                      productPrice: 5.30,
                      description: '2 Hamburgers with a pack of fries',
                      theme1: 'Cheese',
                      only1: 'Gouda Cheese',
                      only2: 'Blue Cheese',
                      theme2: 'Meat',
                      theme3: 'Sauce',
                      only3: 'Pork',
                      only4: 'Chicken',
                      optional1: 'Teriyaki Sauce',
                      optional2: 'Cheese Sauce',
                      optional3: 'Invented Sauce',
                      cant: 0,
                    ),
                    CatalogItem(
                      image: Image.asset('assets/comida/food6.jpg',
                          fit: BoxFit.cover),
                      productName: 'Paella',
                      productPrice: 7,
                      description: 'Paella with Shrimps and eggs',
                      theme1: 'Cheese',
                      only1: 'Gouda Cheese',
                      only2: 'Blue Cheese',
                      theme2: 'Meat',
                      theme3: 'Sauce',
                      only3: 'Pork',
                      only4: 'Chicken',
                      optional1: 'Teriyaki Sauce',
                      optional2: 'Cheese Sauce',
                      optional3: 'Invented Sauce',
                      cant: 0,
                    ),
                    CatalogItem(
                      image: Image.asset('assets/comida/food4.jpg',
                          fit: BoxFit.cover),
                      productName: 'Hamburgers with fries',
                      productPrice: 3.30,
                      description: '1 Hamburgers with a pack of fries',
                      theme1: 'Cheese',
                      only1: 'Gouda Cheese',
                      only2: 'Blue Cheese',
                      theme2: 'Meat',
                      theme3: 'Sauce',
                      only3: 'Pork',
                      only4: 'Chicken',
                      optional1: 'Teriyaki Sauce',
                      optional2: 'Cheese Sauce',
                      optional3: 'Invented Sauce',
                      cant: 0,
                    ),
                    CatalogItem(
                      image: Image.asset('assets/comida/food6.jpg',
                          fit: BoxFit.cover),
                      productName: 'Paella',
                      productPrice: 2,
                      description: 'Paella with Shrimps',
                      theme1: 'Cheese',
                      only1: 'Gouda Cheese',
                      only2: 'Blue Cheese',
                      theme2: 'Meat',
                      theme3: 'Sauce',
                      only3: 'Pork',
                      only4: 'Chicken',
                      optional1: 'Teriyaki Sauce',
                      optional2: 'Cheese Sauce',
                      optional3: 'Invented Sauce',
                      cant: 0,
                    ),
                  ],
                  rebajaImage: Image.asset(
                    'assets/stories/stories1.jpg',
                    fit: BoxFit.cover,
                  ),
                  rebajaDescription: '12% for orders above 20cuc ',
                  rebajaTime: 12,
                  address: 'Acosta/Goicuria & Mayia Rodriguez ',
                  descriptionInfo:
                      'Domino´s Pizza offers the best Fast Food. The best choice with the best prices  ',
                  workingDays: 'No days off',
                  workingHours: '6 AM _ 2 AM',
                ),
              ],
              image: Image.asset(
                'assets/stories/stories2.jpg',
                fit: BoxFit.cover,
              ),
              header: 'Discount for orders above a price',
              title: 'Discount for orders above a price!',
              description: 'Order our special offer and get free drinks',
            ),
            StoriesItem(
              places: [
                PlaceItem(
                  image: Image.asset(
                    'assets/comida/food4.jpg',
                    fit: BoxFit.cover,
                  ),
                  restaurant: 'BurgerKing',
                  logo: Image.asset(
                    'assets/logos/burger_king.jfif',
                    fit: BoxFit.cover,
                  ),
                  rebajaImage: Image.asset(
                    'assets/stories/stories1.jpg',
                    fit: BoxFit.cover,
                  ),
                  rebajaDescription: '15% discount if you buy a combo',
                  rebajaTime: 12,
                  time: 50,
                  price: 2.75,
                  initDelivery: 0,
                  finalDelivery: 2,
                  priceRange: 20,
                  classification1: 'Popular',
                  cant1: 2,
                  classification2: 'Snacks',
                  cant2: 3,
                  classification3: 'Sandwiches',
                  cant3: 7,
                  classification4: 'Drinks',
                  cant4: 3,
                  classification5: 'Hamburgers',
                  cant5: 1,
                  classification6: 'Desserts',
                  cant6: 8,
                  products: [
                    CatalogItem(
                      image: Image.asset('assets/comida/food4.jpg',
                          fit: BoxFit.cover),
                      productName: 'Hamburgers with fries',
                      productPrice: 5.30,
                      description: '2 Hamburgers with a pack of fries',
                      theme1: 'Cheese',
                      only1: 'Gouda Cheese',
                      only2: 'Blue Cheese',
                      theme2: 'Meat',
                      theme3: 'Sauce',
                      only3: 'Pork',
                      only4: 'Chicken',
                      optional1: 'Teriyaki Sauce',
                      optional2: 'Cheese Sauce',
                      optional3: 'Invented Sauce',
                      cant: 0,
                    ),
                    CatalogItem(
                      image: Image.asset('assets/comida/food6.jpg',
                          fit: BoxFit.cover),
                      productName: 'Paella',
                      productPrice: 7,
                      description: 'Paella with Shrimps and eggs',
                      theme1: 'Cheese',
                      only1: 'Gouda Cheese',
                      only2: 'Blue Cheese',
                      theme2: 'Meat',
                      theme3: 'Sauce',
                      only3: 'Pork',
                      only4: 'Chicken',
                      optional1: 'Teriyaki Sauce',
                      optional2: 'Cheese Sauce',
                      optional3: 'Invented Sauce',
                      cant: 0,
                    ),
                    CatalogItem(
                      image: Image.asset('assets/comida/food4.jpg',
                          fit: BoxFit.cover),
                      productName: 'Hamburgers with fries',
                      productPrice: 3.30,
                      description: '1 Hamburgers with a pack of fries',
                      theme1: 'Cheese',
                      only1: 'Gouda Cheese',
                      only2: 'Blue Cheese',
                      theme2: 'Meat',
                      theme3: 'Sauce',
                      only3: 'Pork',
                      only4: 'Chicken',
                      optional1: 'Teriyaki Sauce',
                      optional2: 'Cheese Sauce',
                      optional3: 'Invented Sauce',
                      cant: 0,
                    ),
                    CatalogItem(
                      image: Image.asset('assets/comida/food6.jpg',
                          fit: BoxFit.cover),
                      productName: 'Paella',
                      productPrice: 2,
                      description: 'Paella with Shrimps',
                      theme1: 'Cheese',
                      only1: 'Gouda Cheese',
                      only2: 'Blue Cheese',
                      theme2: 'Meat',
                      theme3: 'Sauce',
                      only3: 'Pork',
                      only4: 'Chicken',
                      optional1: 'Teriyaki Sauce',
                      optional2: 'Cheese Sauce',
                      optional3: 'Invented Sauce',
                      cant: 0,
                    ),
                  ],
                  address: 'Acosta/Goicuria & Mayia Rodriguez ',
                  descriptionInfo:
                      'Burger King offers the best Fast Food. The best choice with the best prices. We have food quality, and reliable suppliers. We are everyone´s preference.    ',
                  workingDays: 'No days off',
                  workingHours: '6 AM _ 2 AM',
                ),
                PlaceItem(
                  image: Image.asset(
                    'assets/comida/food4.jpg',
                    fit: BoxFit.cover,
                  ),
                  restaurant: 'BurgerKing',
                  logo: Image.asset(
                    'assets/logos/burger_king.jfif',
                    fit: BoxFit.cover,
                  ),
                  rebajaImage: Image.asset(
                    'assets/stories/stories1.jpg',
                    fit: BoxFit.cover,
                  ),
                  rebajaDescription: '15% discount if you buy a combo',
                  rebajaTime: 12,
                  time: 50,
                  price: 2.75,
                  initDelivery: 0,
                  finalDelivery: 2,
                  priceRange: 20,
                  classification1: 'Popular',
                  cant1: 2,
                  classification2: 'Snacks',
                  cant2: 3,
                  classification3: 'Sandwiches',
                  cant3: 7,
                  classification4: 'Drinks',
                  cant4: 3,
                  classification5: 'Hamburgers',
                  cant5: 1,
                  classification6: 'Desserts',
                  cant6: 8,
                  products: [
                    CatalogItem(
                      image: Image.asset('assets/comida/food4.jpg',
                          fit: BoxFit.cover),
                      productName: 'Hamburgers with fries',
                      productPrice: 5.30,
                      description: '2 Hamburgers with a pack of fries',
                      theme1: 'Cheese',
                      only1: 'Gouda Cheese',
                      only2: 'Blue Cheese',
                      theme2: 'Meat',
                      theme3: 'Sauce',
                      only3: 'Pork',
                      only4: 'Chicken',
                      optional1: 'Teriyaki Sauce',
                      optional2: 'Cheese Sauce',
                      optional3: 'Invented Sauce',
                      cant: 0,
                    ),
                    CatalogItem(
                      image: Image.asset('assets/comida/food6.jpg',
                          fit: BoxFit.cover),
                      productName: 'Paella',
                      productPrice: 7,
                      description: 'Paella with Shrimps and eggs',
                      theme1: 'Cheese',
                      only1: 'Gouda Cheese',
                      only2: 'Blue Cheese',
                      theme2: 'Meat',
                      theme3: 'Sauce',
                      only3: 'Pork',
                      only4: 'Chicken',
                      optional1: 'Teriyaki Sauce',
                      optional2: 'Cheese Sauce',
                      optional3: 'Invented Sauce',
                      cant: 0,
                    ),
                    CatalogItem(
                      image: Image.asset('assets/comida/food4.jpg',
                          fit: BoxFit.cover),
                      productName: 'Hamburgers with fries',
                      productPrice: 3.30,
                      description: '1 Hamburgers with a pack of fries',
                      theme1: 'Cheese',
                      only1: 'Gouda Cheese',
                      only2: 'Blue Cheese',
                      theme2: 'Meat',
                      theme3: 'Sauce',
                      only3: 'Pork',
                      only4: 'Chicken',
                      optional1: 'Teriyaki Sauce',
                      optional2: 'Cheese Sauce',
                      optional3: 'Invented Sauce',
                      cant: 0,
                    ),
                    CatalogItem(
                      image: Image.asset('assets/comida/food6.jpg',
                          fit: BoxFit.cover),
                      productName: 'Paella',
                      productPrice: 2,
                      description: 'Paella with Shrimps',
                      theme1: 'Cheese',
                      only1: 'Gouda Cheese',
                      only2: 'Blue Cheese',
                      theme2: 'Meat',
                      theme3: 'Sauce',
                      only3: 'Pork',
                      only4: 'Chicken',
                      optional1: 'Teriyaki Sauce',
                      optional2: 'Cheese Sauce',
                      optional3: 'Invented Sauce',
                      cant: 0,
                    ),
                  ],
                  address: 'Acosta/Goicuria & Mayia Rodriguez ',
                  descriptionInfo:
                      'Burger King offers the best Fast Food. The best choice with the best prices. We have food quality, and reliable suppliers. We are everyone´s preference.    ',
                  workingDays: 'No days off',
                  workingHours: '6 AM _ 2 AM',
                ),
              ],
              image: Image.asset(
                'assets/stories/stories3.jpg',
                fit: BoxFit.cover,
              ),
              header: '15% discount if you buy a combo',
              title: '15% discount if you buy a combo!',
              description: 'Collect some points and earn a free meal',
            ),
            StoriesItem(
              places: [
                PlaceItem(
                  image: Image.asset(
                    'assets/comida/food7.jpg',
                    fit: BoxFit.cover,
                  ),
                  restaurant: 'Dominos´s Pizza',
                  logo: Image.asset(
                    'assets/logos/dominos_pizza.png',
                    fit: BoxFit.cover,
                  ),
                  time: 30,
                  price: 4.25,
                  initDelivery: 2,
                  finalDelivery: 5,
                  priceRange: 25,
                  classification1: 'Popular',
                  cant1: 2,
                  classification2: 'Snacks',
                  cant2: 4,
                  classification3: 'Salads',
                  cant3: 9,
                  classification4: 'Drinks',
                  cant4: 3,
                  classification5: 'Pizzas',
                  cant5: 5,
                  classification6: 'Desserts',
                  cant6: 2,
                  products: [
                    CatalogItem(
                      image: Image.asset('assets/comida/food4.jpg',
                          fit: BoxFit.cover),
                      productName: 'Hamburgers with fries',
                      productPrice: 5.30,
                      description: '2 Hamburgers with a pack of fries',
                      theme1: 'Cheese',
                      only1: 'Gouda Cheese',
                      only2: 'Blue Cheese',
                      theme2: 'Meat',
                      theme3: 'Sauce',
                      only3: 'Pork',
                      only4: 'Chicken',
                      optional1: 'Teriyaki Sauce',
                      optional2: 'Cheese Sauce',
                      optional3: 'Invented Sauce',
                      cant: 0,
                    ),
                    CatalogItem(
                      image: Image.asset('assets/comida/food6.jpg',
                          fit: BoxFit.cover),
                      productName: 'Paella',
                      productPrice: 7,
                      description: 'Paella with Shrimps and eggs',
                      theme1: 'Cheese',
                      only1: 'Gouda Cheese',
                      only2: 'Blue Cheese',
                      theme2: 'Meat',
                      theme3: 'Sauce',
                      only3: 'Pork',
                      only4: 'Chicken',
                      optional1: 'Teriyaki Sauce',
                      optional2: 'Cheese Sauce',
                      optional3: 'Invented Sauce',
                      cant: 0,
                    ),
                    CatalogItem(
                      image: Image.asset('assets/comida/food4.jpg',
                          fit: BoxFit.cover),
                      productName: 'Hamburgers with fries',
                      productPrice: 3.30,
                      description: '1 Hamburgers with a pack of fries',
                      theme1: 'Cheese',
                      only1: 'Gouda Cheese',
                      only2: 'Blue Cheese',
                      theme2: 'Meat',
                      theme3: 'Sauce',
                      only3: 'Pork',
                      only4: 'Chicken',
                      optional1: 'Teriyaki Sauce',
                      optional2: 'Cheese Sauce',
                      optional3: 'Invented Sauce',
                      cant: 0,
                    ),
                    CatalogItem(
                      image: Image.asset('assets/comida/food6.jpg',
                          fit: BoxFit.cover),
                      productName: 'Paella',
                      productPrice: 2,
                      description: 'Paella with Shrimps',
                      theme1: 'Cheese',
                      only1: 'Gouda Cheese',
                      only2: 'Blue Cheese',
                      theme2: 'Meat',
                      theme3: 'Sauce',
                      only3: 'Pork',
                      only4: 'Chicken',
                      optional1: 'Teriyaki Sauce',
                      optional2: 'Cheese Sauce',
                      optional3: 'Invented Sauce',
                      cant: 0,
                    ),
                  ],
                  rebajaImage: Image.asset(
                    'assets/stories/stories1.jpg',
                    fit: BoxFit.cover,
                  ),
                  rebajaDescription: '12% for orders above 20cuc ',
                  rebajaTime: 12,
                  address: 'Acosta/Goicuria & Mayia Rodriguez ',
                  descriptionInfo:
                      'Domino´s Pizza offers the best Fast Food. The best choice with the best prices  ',
                  workingDays: 'No days off',
                  workingHours: '6 AM _ 2 AM',
                ),
                PlaceItem(
                  image: Image.asset(
                    'assets/comida/food7.jpg',
                    fit: BoxFit.cover,
                  ),
                  restaurant: 'Dominos´s Pizza',
                  logo: Image.asset(
                    'assets/logos/dominos_pizza.png',
                    fit: BoxFit.cover,
                  ),
                  time: 30,
                  price: 4.25,
                  initDelivery: 2,
                  finalDelivery: 5,
                  priceRange: 25,
                  classification1: 'Popular',
                  cant1: 2,
                  classification2: 'Snacks',
                  cant2: 4,
                  classification3: 'Salads',
                  cant3: 9,
                  classification4: 'Drinks',
                  cant4: 3,
                  classification5: 'Pizzas',
                  cant5: 5,
                  classification6: 'Desserts',
                  cant6: 2,
                  products: [
                    CatalogItem(
                      image: Image.asset('assets/comida/food4.jpg',
                          fit: BoxFit.cover),
                      productName: 'Hamburgers with fries',
                      productPrice: 5.30,
                      description: '2 Hamburgers with a pack of fries',
                      theme1: 'Cheese',
                      only1: 'Gouda Cheese',
                      only2: 'Blue Cheese',
                      theme2: 'Meat',
                      theme3: 'Sauce',
                      only3: 'Pork',
                      only4: 'Chicken',
                      optional1: 'Teriyaki Sauce',
                      optional2: 'Cheese Sauce',
                      optional3: 'Invented Sauce',
                      cant: 0,
                    ),
                    CatalogItem(
                      image: Image.asset('assets/comida/food6.jpg',
                          fit: BoxFit.cover),
                      productName: 'Paella',
                      productPrice: 7,
                      description: 'Paella with Shrimps and eggs',
                      theme1: 'Cheese',
                      only1: 'Gouda Cheese',
                      only2: 'Blue Cheese',
                      theme2: 'Meat',
                      theme3: 'Sauce',
                      only3: 'Pork',
                      only4: 'Chicken',
                      optional1: 'Teriyaki Sauce',
                      optional2: 'Cheese Sauce',
                      optional3: 'Invented Sauce',
                      cant: 0,
                    ),
                    CatalogItem(
                      image: Image.asset('assets/comida/food4.jpg',
                          fit: BoxFit.cover),
                      productName: 'Hamburgers with fries',
                      productPrice: 3.30,
                      description: '1 Hamburgers with a pack of fries',
                      theme1: 'Cheese',
                      only1: 'Gouda Cheese',
                      only2: 'Blue Cheese',
                      theme2: 'Meat',
                      theme3: 'Sauce',
                      only3: 'Pork',
                      only4: 'Chicken',
                      optional1: 'Teriyaki Sauce',
                      optional2: 'Cheese Sauce',
                      optional3: 'Invented Sauce',
                      cant: 0,
                    ),
                    CatalogItem(
                      image: Image.asset('assets/comida/food6.jpg',
                          fit: BoxFit.cover),
                      productName: 'Paella',
                      productPrice: 2,
                      description: 'Paella with Shrimps',
                      theme1: 'Cheese',
                      only1: 'Gouda Cheese',
                      only2: 'Blue Cheese',
                      theme2: 'Meat',
                      theme3: 'Sauce',
                      only3: 'Pork',
                      only4: 'Chicken',
                      optional1: 'Teriyaki Sauce',
                      optional2: 'Cheese Sauce',
                      optional3: 'Invented Sauce',
                      cant: 0,
                    ),
                  ],
                  rebajaImage: Image.asset(
                    'assets/stories/stories1.jpg',
                    fit: BoxFit.cover,
                  ),
                  rebajaDescription: '12% for orders above 20cuc ',
                  rebajaTime: 12,
                  address: 'Acosta/Goicuria & Mayia Rodriguez ',
                  descriptionInfo:
                      'Domino´s Pizza offers the best Fast Food. The best choice with the best prices  ',
                  workingDays: 'No days off',
                  workingHours: '6 AM _ 2 AM',
                ),
              ],
              image: Image.asset(
                'assets/stories/stories4.jpg',
                fit: BoxFit.cover,
              ),
              header: '12% for orders above 20cuc',
              title: '12% for orders above 20cuc!',
              description: 'Order our special offer and get free drinks',
            ),
          ],
        ),
      ),
    );
  }
}
